spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

jira:
  link: ${JIRA_LINK}
  dashboards: ${JIRA_DASHBOARDS}

settings:
  number-of-review-stages: ${NUMBER_OF_REVIEW_STAGES}

logging:
  level:
    org:
      springframework:
        web: ${LOGGING_LEVEL}